import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Search from "@/components/Search";
import "./globals.css";
import Providers from "./Providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {/* Context only works on client side. So for theme we need an extra provider. 
        However anything inside the Providers is still server side (Next13)*/}
        <Providers>
          {/* Header */}
          <Header />
          {/* Nav */}
          <Navbar />
          {/* Search */}
          <Search />
          {children}
        </Providers>
      </body>
    </html>
  );
}
